

def TestNumber(input : str, maxSignificant : int) -> float: ...

class Calculator:
    Significance : int
    FinalSignificance : int
    RootSignificance : int
    
    def __init__(self, maxSignificance : int) -> None: ...
    def Calculate_double(self, input : str) -> float: ...
    def Calculate_string(self, input : str) -> str: ...
