

def TestNumber(input : str, maxSignificant : int) -> float: ...

class Calculator:
    Significance : int
    FinalSignificance : int
    RootSignificance : int
    
    def __init__(self, maxSignificance : int) -> None: ...
    def Calculate(self, input : str) -> None: ...
    def Calculate_double(self) -> float: ...
    def Calculate_scientific_string(self) -> str: ...
    def Calculate_string(self) -> str: ...
    def Get_last_error(self) -> str: ...
    def Get_variable_names(self) -> list[str]: ...
    def Delete_variable(self, name : str) -> None: ...
