

def TestNumber(input : str, maxSignificant : int) -> float: ...

class Calculator:
    maxSignificant : int
    def __init__(self, maxSignificant : int) -> None: ...
    def Calculate_double(self, input : str) -> float: ...
    def Calculate_string(self, input : str) -> str: ...
